<?xml version="1.0" encoding="utf-8"?><Database Name="GameDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-9U8TJO4\SQLEXPRESS;Initial Catalog=GameDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GameDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TblMember" Member="TblMembers">
    <Type Name="TblMember">
      <Column Name="UserID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNo" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="RefCode" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="RefCodeReg" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="VipLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Promotion" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="GroupLeaderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Association Name="TblMember_TblGameAccount" Member="TblGameAccounts" ThisKey="UserName" OtherKey="MemberUserName" Type="TblGameAccount" />
      <Association Name="TblMember_TblMemberBank" Member="TblMemberBanks" ThisKey="UserName" OtherKey="MemberUserName" Type="TblMemberBank" />
      <Association Name="TblTransaction_TblMember" Member="TblTransaction" ThisKey="UserName" OtherKey="UserName" Type="TblTransaction" IsForeignKey="true" />
      <Association Name="TblTransfer_TblMember" Member="TblTransfer" ThisKey="UserName" OtherKey="UserName" Type="TblTransfer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblGameAccount" Member="TblGameAccounts">
    <Type Name="TblGameAccount">
      <Column Name="GameID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Product" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MemberUserName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Association Name="TblMember_TblGameAccount" Member="TblMember" ThisKey="MemberUserName" OtherKey="UserName" Type="TblMember" IsForeignKey="true" />
      <Association Name="TblTransaction_TblGameAccount" Member="TblTransaction" ThisKey="Product,UserName" OtherKey="Product,ProductUserName" Type="TblTransaction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblMemberBank" Member="TblMemberBanks">
    <Type Name="TblMemberBank">
      <Column Name="MemberBankID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MemberUserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="TblMember_TblMemberBank" Member="TblMember" ThisKey="MemberUserName" OtherKey="UserName" Type="TblMember" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblTransaction" Member="TblTransactions">
    <Type Name="TblTransaction">
      <Column Name="TransactionID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Method" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Debit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Promotion" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Product" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ProductUserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Bank" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UploadFile" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Association Name="TblTransaction_TblMember" Member="TblMembers" ThisKey="UserName" OtherKey="UserName" Type="TblMember" />
      <Association Name="TblTransaction_TblGameAccount" Member="TblGameAccounts" ThisKey="Product,ProductUserName" OtherKey="Product,UserName" Type="TblGameAccount" />
    </Type>
  </Table>
  <Table Name="dbo.TblTransfer" Member="TblTransfers">
    <Type Name="TblTransfer">
      <Column Name="TransferID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransferDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FromProduct" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FromUserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ToProduct" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ToUserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TblTransfer_TblMember" Member="TblMembers" ThisKey="UserName" OtherKey="UserName" Type="TblMember" />
    </Type>
  </Table>
  <Table Name="dbo.TblPromotion" Member="TblPromotions">
    <Type Name="TblPromotion">
      <Column Name="PromoID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PromoName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PromoType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PromoPercent" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MaxPayout" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EnglishName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="ChineseName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="MalayName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="EnglishTNC" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="ChineseTNC" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="MalayTNC" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblBank" Member="TblBanks">
    <Type Name="TblBank">
      <Column Name="BankID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankWeb" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="MinAmount" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MaxAmount" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>