<?xml version="1.0" encoding="utf-8"?><Database Name="GameDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-9U8TJO4\SQLEXPRESS;Initial Catalog=GameDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GameDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TblSlider" Member="TblSliders">
    <Type Name="TblSlider">
      <Column Name="SliderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SliderName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="LinkUrl" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="SliderImage" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblLog" Member="TblLogs">
    <Type Name="TblLog">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogMember" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="LogIP" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LogType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblTransRemark" Member="TblTransRemarks">
    <Type Name="TblTransRemark">
      <Column Name="TrID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TRemark" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblTRejectReason" Member="TblTRejectReasons">
    <Type Name="TblTRejectReason">
      <Column Name="TrrID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrReason" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblSummary" Member="TblSummaries">
    <Type Name="TblSummary">
      <Column Name="SummaryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Debit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Promotion" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SummaryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblBankRecord" Member="TblBankRecords">
    <Type Name="TblBankRecord">
      <Column Name="BRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Debit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="RecordDatetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblProduct" Member="TblProducts">
    <Type Name="TblProduct">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ProductAlias" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AndroidLink" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="iOSLink" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="WindowsLink" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="WebsiteUrl" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="ProductImage" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CatSlot" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CatLive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CatSport" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CatFish" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CatPoker" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CatRNG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CatOther" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblGameAccount" Member="TblGameAccounts">
    <Type Name="TblGameAccount">
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MemberUserName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblMember" Member="TblMembers">
    <Type Name="TblMember">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNo" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="RefCode" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="RefCodeReg" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="VipLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Promotion" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="GroupLeaderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Affiliate" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="BankName" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblUser" Member="TblUsers">
    <Type Name="TblUser">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserRole" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginIP" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblTransfer" Member="TblTransfers">
    <Type Name="TblTransfer">
      <Column Name="TransferID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransferDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FromProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FromUserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ToProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ToUserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="ApproveByUser" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ApproveDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblBank" Member="TblBanks">
    <Type Name="TblBank">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankWeb" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="MinCredit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MaxCredit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MinDebit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MaxDebit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="BankLogo" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AllowCredit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowDebit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblContact" Member="TblContacts">
    <Type Name="TblContact">
      <Column Name="ContactID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContactType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ContactTitle" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="FaIcon" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowFooter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowContactPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowProductPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblPromotion" Member="TblPromotions">
    <Type Name="TblPromotion">
      <Column Name="PromoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PromoName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PromoType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PromoPercent" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MaxPayout" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EnglishName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="ChineseName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="MalayName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="PromoFile" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PromoImage" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AllowOnDeposit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TblTransaction" Member="TblTransactions">
    <Type Name="TblTransaction">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Method" Type="System.String" DbType="NChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="TransType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Debit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Promotion" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Channel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductUserName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Bank" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="UploadFile" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Reference" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="ApproveByUser" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ApproveDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="TransactionDateUser" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ApproveBankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>